---
- hosts: localhost
  connection: local
  vars:
    ssh_key: nginx
    num_nodes: 2
    security_group_name: nginx
    template: Linux Debian 8 64-bit 10G Disk (2016-10-28-ec67e5) 
    instance_type: Micro

  roles:
    - common
    - infra
